# Generated by Django 5.1 on 2024-08-29 20:40

import api.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label of the wallet')),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=30, verbose_name='Balance of the Wallet')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['label'], name='api_wallet_label_612641_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_non_negative')],
            },
            bases=(api.models.SoftDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Transaction Amount')),
                ('is_deleted', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['txid'], name='api_transac_txid_a6320a_idx')],
            },
            bases=(api.models.SoftDeleteMixin, models.Model),
        ),
    ]
